// Mocks generated by Mockito 5.4.6 from annotations
// in number_list/test/features/home/presentation/bloc/home_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:number_list/core/errors/failure.dart' as _i5;
import 'package:number_list/features/home/domain/entities/number_item.dart'
    as _i6;
import 'package:number_list/features/home/domain/repositories/numbers_repository.dart'
    as _i2;
import 'package:number_list/features/home/domain/usecases/calculate_total_usecase.dart'
    as _i10;
import 'package:number_list/features/home/domain/usecases/get_numbers_usecase.dart'
    as _i3;
import 'package:number_list/features/home/domain/usecases/increment_number_usecase.dart'
    as _i8;
import 'package:number_list/features/home/domain/usecases/reset_numbers_usecase.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNumbersRepository_0 extends _i1.SmartFake
    implements _i2.NumbersRepository {
  _FakeNumbersRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetNumbersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNumbersUseCase extends _i1.Mock implements _i3.GetNumbersUseCase {
  MockGetNumbersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NumbersRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNumbersRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.NumbersRepository);

  @override
  _i4.Either<_i5.Failure, List<_i6.NumberItem>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i7
                .dummyValue<_i4.Either<_i5.Failure, List<_i6.NumberItem>>>(
                  this,
                  Invocation.method(#call, []),
                ),
          )
          as _i4.Either<_i5.Failure, List<_i6.NumberItem>>);
}

/// A class which mocks [IncrementNumberUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockIncrementNumberUseCase extends _i1.Mock
    implements _i8.IncrementNumberUseCase {
  MockIncrementNumberUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NumbersRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNumbersRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.NumbersRepository);

  @override
  _i4.Either<_i5.Failure, List<_i6.NumberItem>> call(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#call, [index]),
            returnValue: _i7
                .dummyValue<_i4.Either<_i5.Failure, List<_i6.NumberItem>>>(
                  this,
                  Invocation.method(#call, [index]),
                ),
          )
          as _i4.Either<_i5.Failure, List<_i6.NumberItem>>);
}

/// A class which mocks [ResetNumbersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetNumbersUseCase extends _i1.Mock
    implements _i9.ResetNumbersUseCase {
  MockResetNumbersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NumbersRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNumbersRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.NumbersRepository);

  @override
  _i4.Either<_i5.Failure, List<_i6.NumberItem>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i7
                .dummyValue<_i4.Either<_i5.Failure, List<_i6.NumberItem>>>(
                  this,
                  Invocation.method(#call, []),
                ),
          )
          as _i4.Either<_i5.Failure, List<_i6.NumberItem>>);
}

/// A class which mocks [CalculateTotalUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalculateTotalUseCase extends _i1.Mock
    implements _i10.CalculateTotalUseCase {
  MockCalculateTotalUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int call(List<_i6.NumberItem>? numbers) =>
      (super.noSuchMethod(Invocation.method(#call, [numbers]), returnValue: 0)
          as int);
}
